
/* Drop Tables */

DROP TABLE Interested;
DROP TABLE TerritoryHistory;
DROP TABLE publisher_privilege;
DROP TABLE Subject;
DROP TABLE TerritoriesAssignments;
DROP TABLE Publisher;
DROP TABLE PublishingGroup;
DROP TABLE Congregation;
DROP TABLE Contact;
DROP TABLE AddressType;
DROP TABLE MinistryWeek;
DROP TABLE Privilege;
DROP TABLE Sexe;
DROP TABLE Status;
DROP TABLE SubjectType;
DROP TABLE Territory;




/* Create Tables */

CREATE TABLE AddressType
(
	addressTypeId int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	addressType varchar(32) NOT NULL UNIQUE,
	PRIMARY KEY (addressTypeId)
);


CREATE TABLE Congregation
(
	congregation_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	congregation_name varchar(64) NOT NULL UNIQUE,
	congregation_language varchar(64) NOT NULL,
	congregation_contact int UNIQUE,
	PRIMARY KEY (congregation_id)
);


CREATE TABLE Contact
(
	contact_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	cell_phone varchar(32),
	phone varchar(32),
	skype_id varchar(32),
	email varchar(64),
	street varchar(64),
	house varchar(64),
	appartment varchar(10),
	postal_code varchar(10),
	city varchar(64),
	country varchar(64),
	territory_id int,
	addressTypeId int,
	PRIMARY KEY (contact_id));


CREATE TABLE Interested
(
	interested_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	first_name varchar(64) NOT NULL,
	last_name varchar(64) NOT NULL,
	last_visit date,
	note varchar(512),
	french boolean,
	contact_id int UNIQUE,
	PRIMARY KEY (interested_id)
);


CREATE TABLE MinistryWeek
(
	week_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	week_start date NOT NULL,
	week_end date NOT NULL,
	PRIMARY KEY (week_id)
);


CREATE TABLE Privilege
(
	privilege_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	privilege varchar(64) NOT NULL UNIQUE,
	PRIMARY KEY (privilege_id)
);


CREATE TABLE Publisher
(
	publisher_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	first_name varchar(64) NOT NULL,
	last_name varchar(64) NOT NULL,
	birthday date,
	congregation int,
	status_id int,
	sexe_id int,
	contact_id int,
	group_id int,
	PRIMARY KEY (publisher_id)
);


CREATE TABLE publisher_privilege
(
	publisher_id int NOT NULL,
	privilege_id int NOT NULL
);


CREATE TABLE PublishingGroup
(
	group_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(32) UNIQUE,
	congregation_id int,
	PRIMARY KEY (group_id)
);


CREATE TABLE Sexe
(
	sexe_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	sexe varchar(64) NOT NULL UNIQUE,
	PRIMARY KEY (sexe_id)
);


CREATE TABLE Status
(
	status_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	status varchar(64) NOT NULL UNIQUE,
	PRIMARY KEY (status_id)
);


CREATE TABLE Subject
(
	subject_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	subject_title varchar(128) NOT NULL,
	subject_sources varchar(256),
	remark varchar(64),
	week int,
	publisher_id int,
	subject_type int,
	PRIMARY KEY (subject_id)
);


CREATE TABLE SubjectType
(
	subject_type_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	subject_name varchar(64) NOT NULL UNIQUE,
	subject_fixed_duration time NOT NULL,
	PRIMARY KEY (subject_type_id)
);


CREATE TABLE TerritoriesAssignments
(
	territory_assignment_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	publisher_id int NOT NULL,
	territory_id int NOT NULL,
	assignment_date date DEFAULT CURRENT_TIMESTAMP NOT NULL,
	return_date date,
	last_work_date date,
	PRIMARY KEY (territory_assignment_id)
);


CREATE TABLE Territory
(
	territory_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	bounds varchar(4096),
	name varchar(64) NOT NULL,
	code varchar(64) NOT NULL,
	picture binary,
	territory_type varchar(64) DEFAULT '',
	city varchar(64),
	group_name varchar(64),
	status varchar(32),
	PRIMARY KEY (territory_id)
);


CREATE TABLE TerritoryHistory
(
	history_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	publisher_id int NOT NULL,
	territory_id int NOT NULL,
	action_date date NOT NULL,
	action_description varchar(64),
	PRIMARY KEY (history_id)
);



/* Create Foreign Keys */

ALTER TABLE Contact
	ADD FOREIGN KEY (addressTypeId)
	REFERENCES AddressType (addressTypeId)
	ON UPDATE CASCADE
	ON DELETE SET NULL
;


ALTER TABLE Publisher
	ADD FOREIGN KEY (congregation)
	REFERENCES Congregation (congregation_id)
	ON UPDATE CASCADE
	ON DELETE SET NULL
;


ALTER TABLE PublishingGroup
	ADD FOREIGN KEY (congregation_id)
	REFERENCES Congregation (congregation_id)
	ON UPDATE CASCADE
	ON DELETE SET NULL
;


ALTER TABLE Interested
	ADD FOREIGN KEY (contact_id)
	REFERENCES Contact (contact_id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE Congregation
	ADD FOREIGN KEY (congregation_contact)
	REFERENCES Contact (contact_id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE Publisher
	ADD FOREIGN KEY (contact_id)
	REFERENCES Contact (contact_id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE Subject
	ADD FOREIGN KEY (week)
	REFERENCES MinistryWeek (week_id)
	ON UPDATE CASCADE
	ON DELETE SET NULL
;


ALTER TABLE publisher_privilege
	ADD FOREIGN KEY (privilege_id)
	REFERENCES Privilege (privilege_id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE TerritoryHistory
	ADD FOREIGN KEY (publisher_id)
	REFERENCES Publisher (publisher_id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE publisher_privilege
	ADD FOREIGN KEY (publisher_id)
	REFERENCES Publisher (publisher_id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE Subject
	ADD FOREIGN KEY (publisher_id)
	REFERENCES Publisher (publisher_id)
	ON UPDATE CASCADE
	ON DELETE SET NULL
;


ALTER TABLE TerritoriesAssignments
	ADD FOREIGN KEY (publisher_id)
	REFERENCES Publisher (publisher_id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE Publisher
	ADD FOREIGN KEY (group_id)
	REFERENCES PublishingGroup (group_id)
	ON UPDATE CASCADE
	ON DELETE SET NULL
;


ALTER TABLE Publisher
	ADD FOREIGN KEY (sexe_id)
	REFERENCES Sexe (sexe_id)
	ON UPDATE CASCADE
	ON DELETE SET NULL
;


ALTER TABLE Publisher
	ADD FOREIGN KEY (status_id)
	REFERENCES Status (status_id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE Subject
	ADD FOREIGN KEY (subject_type)
	REFERENCES SubjectType (subject_type_id)
	ON UPDATE CASCADE
	ON DELETE SET NULL
;


ALTER TABLE Contact
	ADD FOREIGN KEY (territory_id)
	REFERENCES Territory (territory_id)
	ON UPDATE CASCADE
	ON DELETE SET NULL
;


ALTER TABLE TerritoriesAssignments
	ADD FOREIGN KEY (territory_id)
	REFERENCES Territory (territory_id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE TerritoryHistory
	ADD FOREIGN KEY (territory_id)
	REFERENCES Territory (territory_id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;



