package jw.ministry.soft.modules.data.dto;

// Generated 18 mai 2015 18:28:53 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Addresstype generated by hbm2java
 */
public class Addresstype implements java.io.Serializable {

	private Integer addresstypeid;
	private String addresstype;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Addresstype() {
	}

	public Addresstype(String addresstype) {
		this.addresstype = addresstype;
	}

	public Addresstype(String addresstype, Set<Contact> contacts) {
		this.addresstype = addresstype;
		this.contacts = contacts;
	}

	public Integer getAddresstypeid() {
		return this.addresstypeid;
	}

	public void setAddresstypeid(Integer addresstypeid) {
		this.addresstypeid = addresstypeid;
	}

	public String getAddresstype() {
		return this.addresstype;
	}

	public void setAddresstype(String addresstype) {
		this.addresstype = addresstype;
	}

	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

}
