package jw.ministry.soft.modules.data.dto;

// Generated 18 mai 2015 18:28:53 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Congregation generated by hbm2java
 */
public class Congregation implements java.io.Serializable {

	private Integer congregationId;
	private Contact contact;
	private String congregationName;
	private String congregationLanguage;
	private Set<Publishinggroup> publishinggroups = new HashSet<Publishinggroup>(
			0);
	private Set<Publisher> publishers = new HashSet<Publisher>(0);

	public Congregation() {
	}

	public Congregation(String congregationName, String congregationLanguage) {
		this.congregationName = congregationName;
		this.congregationLanguage = congregationLanguage;
	}

	public Congregation(Contact contact, String congregationName,
			String congregationLanguage, Set<Publishinggroup> publishinggroups,
			Set<Publisher> publishers) {
		this.contact = contact;
		this.congregationName = congregationName;
		this.congregationLanguage = congregationLanguage;
		this.publishinggroups = publishinggroups;
		this.publishers = publishers;
	}

	public Integer getCongregationId() {
		return this.congregationId;
	}

	public void setCongregationId(Integer congregationId) {
		this.congregationId = congregationId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public String getCongregationName() {
		return this.congregationName;
	}

	public void setCongregationName(String congregationName) {
		this.congregationName = congregationName;
	}

	public String getCongregationLanguage() {
		return this.congregationLanguage;
	}

	public void setCongregationLanguage(String congregationLanguage) {
		this.congregationLanguage = congregationLanguage;
	}

	public Set<Publishinggroup> getPublishinggroups() {
		return this.publishinggroups;
	}

	public void setPublishinggroups(Set<Publishinggroup> publishinggroups) {
		this.publishinggroups = publishinggroups;
	}

	public Set<Publisher> getPublishers() {
		return this.publishers;
	}

	public void setPublishers(Set<Publisher> publishers) {
		this.publishers = publishers;
	}

}
