package jw.ministry.soft.modules.data.dto;

// Generated 18 mai 2015 18:28:53 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private Integer contactId;
	private Addresstype addresstype;
	private Territory territory;
	private String cellPhone;
	private String phone;
	private String skypeId;
	private String email;
	private String street;
	private String house;
	private String appartment;
	private String postalCode;
	private String city;
	private String country;
	private Set<Congregation> congregations = new HashSet<Congregation>(0);
	private Set<Interested> interesteds = new HashSet<Interested>(0);
	private Set<Publisher> publishers = new HashSet<Publisher>(0);

	public Contact() {
	}

	public Contact(Addresstype addresstype, Territory territory,
			String cellPhone, String phone, String skypeId, String email,
			String street, String house, String appartment, String postalCode,
			String city, String country, Set<Congregation> congregations,
			Set<Interested> interesteds, Set<Publisher> publishers) {
		this.addresstype = addresstype;
		this.territory = territory;
		this.cellPhone = cellPhone;
		this.phone = phone;
		this.skypeId = skypeId;
		this.email = email;
		this.street = street;
		this.house = house;
		this.appartment = appartment;
		this.postalCode = postalCode;
		this.city = city;
		this.country = country;
		this.congregations = congregations;
		this.interesteds = interesteds;
		this.publishers = publishers;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public Addresstype getAddresstype() {
		return this.addresstype;
	}

	public void setAddresstype(Addresstype addresstype) {
		this.addresstype = addresstype;
	}

	public Territory getTerritory() {
		return this.territory;
	}

	public void setTerritory(Territory territory) {
		this.territory = territory;
	}

	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getSkypeId() {
		return this.skypeId;
	}

	public void setSkypeId(String skypeId) {
		this.skypeId = skypeId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getHouse() {
		return this.house;
	}

	public void setHouse(String house) {
		this.house = house;
	}

	public String getAppartment() {
		return this.appartment;
	}

	public void setAppartment(String appartment) {
		this.appartment = appartment;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set<Congregation> getCongregations() {
		return this.congregations;
	}

	public void setCongregations(Set<Congregation> congregations) {
		this.congregations = congregations;
	}

	public Set<Interested> getInteresteds() {
		return this.interesteds;
	}

	public void setInteresteds(Set<Interested> interesteds) {
		this.interesteds = interesteds;
	}

	public Set<Publisher> getPublishers() {
		return this.publishers;
	}

	public void setPublishers(Set<Publisher> publishers) {
		this.publishers = publishers;
	}

}
