package jw.ministry.soft.modules.data.dto;

// Generated 18 mai 2015 18:28:53 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Interested generated by hbm2java
 */
public class Interested implements java.io.Serializable {

	private Integer interestedId;
	private Contact contact;
	private String firstName;
	private String lastName;
	private Date lastVisit;
	private String note;
	private Boolean french;

	public Interested() {
	}

	public Interested(String firstName, String lastName) {
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Interested(Contact contact, String firstName, String lastName,
			Date lastVisit, String note, Boolean french) {
		this.contact = contact;
		this.firstName = firstName;
		this.lastName = lastName;
		this.lastVisit = lastVisit;
		this.note = note;
		this.french = french;
	}

	public Integer getInterestedId() {
		return this.interestedId;
	}

	public void setInterestedId(Integer interestedId) {
		this.interestedId = interestedId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getLastVisit() {
		return this.lastVisit;
	}

	public void setLastVisit(Date lastVisit) {
		this.lastVisit = lastVisit;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Boolean getFrench() {
		return this.french;
	}

	public void setFrench(Boolean french) {
		this.french = french;
	}

}
