package jw.ministry.soft.modules.data.dto;

// Generated 24 févr. 2015 07:54:37 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ministryweek generated by hbm2java
 */
public class Ministryweek implements java.io.Serializable {

	private Integer weekId;
	private Date weekStart;
	private Date weekEnd;
	private Set<Subject> subjects = new HashSet<Subject>(0);

	public Ministryweek() {
	}

	public Ministryweek(Date weekStart, Date weekEnd) {
		this.weekStart = weekStart;
		this.weekEnd = weekEnd;
	}

	public Ministryweek(Date weekStart, Date weekEnd, Set<Subject> subjects) {
		this.weekStart = weekStart;
		this.weekEnd = weekEnd;
		this.subjects = subjects;
	}

	public Integer getWeekId() {
		return this.weekId;
	}

	public void setWeekId(Integer weekId) {
		this.weekId = weekId;
	}

	public Date getWeekStart() {
		return this.weekStart;
	}

	public void setWeekStart(Date weekStart) {
		this.weekStart = weekStart;
	}

	public Date getWeekEnd() {
		return this.weekEnd;
	}

	public void setWeekEnd(Date weekEnd) {
		this.weekEnd = weekEnd;
	}

	public Set<Subject> getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set<Subject> subjects) {
		this.subjects = subjects;
	}

}
