package jw.ministry.soft.modules.data.dto;

// Generated 18 mai 2015 18:28:53 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Publishinggroup generated by hbm2java
 */
public class Publishinggroup implements java.io.Serializable {

	private Integer groupId;
	private Congregation congregation;
	private String name;
	private Set<Publisher> publishers = new HashSet<Publisher>(0);

	public Publishinggroup() {
	}

	public Publishinggroup(Congregation congregation, String name,
			Set<Publisher> publishers) {
		this.congregation = congregation;
		this.name = name;
		this.publishers = publishers;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Congregation getCongregation() {
		return this.congregation;
	}

	public void setCongregation(Congregation congregation) {
		this.congregation = congregation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Publisher> getPublishers() {
		return this.publishers;
	}

	public void setPublishers(Set<Publisher> publishers) {
		this.publishers = publishers;
	}

}
