package jw.ministry.soft.modules.data.dto;

// Generated 18 mai 2015 18:28:53 by Hibernate Tools 4.3.1

/**
 * PublisherPrivilegeId generated by hbm2java
 */
public class PublisherPrivilegeId implements java.io.Serializable {

	private int publisherId;
	private int privilegeId;

	public PublisherPrivilegeId() {
	}

	public PublisherPrivilegeId(int publisherId, int privilegeId) {
		this.publisherId = publisherId;
		this.privilegeId = privilegeId;
	}

	public int getPublisherId() {
		return this.publisherId;
	}

	public void setPublisherId(int publisherId) {
		this.publisherId = publisherId;
	}

	public int getPrivilegeId() {
		return this.privilegeId;
	}

	public void setPrivilegeId(int privilegeId) {
		this.privilegeId = privilegeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublisherPrivilegeId))
			return false;
		PublisherPrivilegeId castOther = (PublisherPrivilegeId) other;

		return (this.getPublisherId() == castOther.getPublisherId())
				&& (this.getPrivilegeId() == castOther.getPrivilegeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPublisherId();
		result = 37 * result + this.getPrivilegeId();
		return result;
	}

}
