package jw.ministry.soft.modules.data.dto;

// Generated 24 févr. 2015 07:54:37 by Hibernate Tools 4.3.1

/**
 * PublisherPrivilege generated by hbm2java
 */
public class PublisherPrivilege implements java.io.Serializable {

	private PublisherPrivilegeId id;
	private Privilege privilege;
	private Publisher publisher;

	public PublisherPrivilege() {
	}

	public PublisherPrivilege(PublisherPrivilegeId id, Privilege privilege,
			Publisher publisher) {
		this.id = id;
		this.privilege = privilege;
		this.publisher = publisher;
	}

	public PublisherPrivilegeId getId() {
		return this.id;
	}

	public void setId(PublisherPrivilegeId id) {
		this.id = id;
	}

	public Privilege getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Privilege privilege) {
		this.privilege = privilege;
	}

	public Publisher getPublisher() {
		return this.publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

}
