package jw.ministry.soft.modules.data.dto;

// Generated 24 févr. 2015 07:54:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Sexe generated by hbm2java
 */
public class Sexe implements java.io.Serializable {

	private Integer sexeId;
	private String sexe;
	private Set<Publisher> publishers = new HashSet<Publisher>(0);

	public Sexe() {
	}

	public Sexe(String sexe) {
		this.sexe = sexe;
	}

	public Sexe(String sexe, Set<Publisher> publishers) {
		this.sexe = sexe;
		this.publishers = publishers;
	}

	public Integer getSexeId() {
		return this.sexeId;
	}

	public void setSexeId(Integer sexeId) {
		this.sexeId = sexeId;
	}

	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public Set<Publisher> getPublishers() {
		return this.publishers;
	}

	public void setPublishers(Set<Publisher> publishers) {
		this.publishers = publishers;
	}

}
