package jw.ministry.soft.modules.data.dto;

// Generated 24 févr. 2015 07:54:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private Integer statusId;
	private String status;
	private Set<Publisher> publishers = new HashSet<Publisher>(0);

	public Status() {
	}

	public Status(String status) {
		this.status = status;
	}

	public Status(String status, Set<Publisher> publishers) {
		this.status = status;
		this.publishers = publishers;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<Publisher> getPublishers() {
		return this.publishers;
	}

	public void setPublishers(Set<Publisher> publishers) {
		this.publishers = publishers;
	}

}
