package jw.ministry.soft.modules.data.dto;

// Generated 24 févr. 2015 21:18:01 by Hibernate Tools 4.3.1

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	private Integer subjectId;
	private Ministryweek ministryweek;
	private Publisher publisher;
	private Subjecttype subjecttype;
	private String subjectTitle;
	private String subjectSources;
	private String remark;

	public Subject() {
	}

	public Subject(String subjectTitle) {
		this.subjectTitle = subjectTitle;
	}

	public Subject(Ministryweek ministryweek, Publisher publisher,
			Subjecttype subjecttype, String subjectTitle,
			String subjectSources, String remark) {
		this.ministryweek = ministryweek;
		this.publisher = publisher;
		this.subjecttype = subjecttype;
		this.subjectTitle = subjectTitle;
		this.subjectSources = subjectSources;
		this.remark = remark;
	}

	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	public Ministryweek getMinistryweek() {
		return this.ministryweek;
	}

	public void setMinistryweek(Ministryweek ministryweek) {
		this.ministryweek = ministryweek;
	}

	public Publisher getPublisher() {
		return this.publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	public Subjecttype getSubjecttype() {
		return this.subjecttype;
	}

	public void setSubjecttype(Subjecttype subjecttype) {
		this.subjecttype = subjecttype;
	}

	public String getSubjectTitle() {
		return this.subjectTitle;
	}

	public void setSubjectTitle(String subjectTitle) {
		this.subjectTitle = subjectTitle;
	}

	public String getSubjectSources() {
		return this.subjectSources;
	}

	public void setSubjectSources(String subjectSources) {
		this.subjectSources = subjectSources;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
