package jw.ministry.soft.modules.data.dto;

// Generated 1 juin 2015 18:21:17 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Territoriesassignments generated by hbm2java
 */
public class Territoriesassignments implements java.io.Serializable {

	private Integer territoryAssignmentId;
	private Publisher publisher;
	private Territory territory;
	private Date assignmentDate;
	private Date returnDate;
	private Date lastWorkDate;

	public Territoriesassignments() {
	}

	public Territoriesassignments(Publisher publisher, Territory territory,
			Date assignmentDate) {
		this.publisher = publisher;
		this.territory = territory;
		this.assignmentDate = assignmentDate;
	}

	public Territoriesassignments(Publisher publisher, Territory territory,
			Date assignmentDate, Date returnDate, Date lastWorkDate) {
		this.publisher = publisher;
		this.territory = territory;
		this.assignmentDate = assignmentDate;
		this.returnDate = returnDate;
		this.lastWorkDate = lastWorkDate;
	}

	public Integer getTerritoryAssignmentId() {
		return this.territoryAssignmentId;
	}

	public void setTerritoryAssignmentId(Integer territoryAssignmentId) {
		this.territoryAssignmentId = territoryAssignmentId;
	}

	public Publisher getPublisher() {
		return this.publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	public Territory getTerritory() {
		return this.territory;
	}

	public void setTerritory(Territory territory) {
		this.territory = territory;
	}

	public Date getAssignmentDate() {
		return this.assignmentDate;
	}

	public void setAssignmentDate(Date assignmentDate) {
		this.assignmentDate = assignmentDate;
	}

	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	public Date getLastWorkDate() {
		return this.lastWorkDate;
	}

	public void setLastWorkDate(Date lastWorkDate) {
		this.lastWorkDate = lastWorkDate;
	}

}
