package jw.ministry.soft.modules.data.dto;

// Generated 25 juin 2015 01:39:36 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Territory generated by hbm2java
 */
public class Territory implements java.io.Serializable {

	private Integer territoryId;
	private String bounds;
	private String name;
	private String code;
	private byte[] picture;
	private String territoryType;
	private String city;
	private String groupName;
	private String status;
	private Set<Territoriesassignments> territoriesassignmentses = new HashSet<Territoriesassignments>(
			0);
	private Set<Territoryhistory> territoryhistories = new HashSet<Territoryhistory>(
			0);
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Territory() {
	}

	public Territory(String name, String code) {
		this.name = name;
		this.code = code;
	}

	public Territory(String bounds, String name, String code, byte[] picture,
			String territoryType, String city, String groupName, String status,
			Set<Territoriesassignments> territoriesassignmentses,
			Set<Territoryhistory> territoryhistories, Set<Contact> contacts) {
		this.bounds = bounds;
		this.name = name;
		this.code = code;
		this.picture = picture;
		this.territoryType = territoryType;
		this.city = city;
		this.groupName = groupName;
		this.status = status;
		this.territoriesassignmentses = territoriesassignmentses;
		this.territoryhistories = territoryhistories;
		this.contacts = contacts;
	}

	public Integer getTerritoryId() {
		return this.territoryId;
	}

	public void setTerritoryId(Integer territoryId) {
		this.territoryId = territoryId;
	}

	public String getBounds() {
		return this.bounds;
	}

	public void setBounds(String bounds) {
		this.bounds = bounds;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	public String getTerritoryType() {
		return this.territoryType;
	}

	public void setTerritoryType(String territoryType) {
		this.territoryType = territoryType;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<Territoriesassignments> getTerritoriesassignmentses() {
		return this.territoriesassignmentses;
	}

	public void setTerritoriesassignmentses(
			Set<Territoriesassignments> territoriesassignmentses) {
		this.territoriesassignmentses = territoriesassignmentses;
	}

	public Set<Territoryhistory> getTerritoryhistories() {
		return this.territoryhistories;
	}

	public void setTerritoryhistories(Set<Territoryhistory> territoryhistories) {
		this.territoryhistories = territoryhistories;
	}

	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

}
