package jw.ministry.soft.modules.data.dto;

// Generated 8 juin 2015 16:05:54 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Territoryhistory generated by hbm2java
 */
public class Territoryhistory implements java.io.Serializable {

	private Integer historyId;
	private Publisher publisher;
	private Territory territory;
	private Date actionDate;
	private String actionDescrption;

	public Territoryhistory() {
	}

	public Territoryhistory(Publisher publisher, Territory territory,
			Date actionDate) {
		this.publisher = publisher;
		this.territory = territory;
		this.actionDate = actionDate;
	}

	public Territoryhistory(Publisher publisher, Territory territory,
			Date actionDate, String actionDescrption) {
		this.publisher = publisher;
		this.territory = territory;
		this.actionDate = actionDate;
		this.actionDescrption = actionDescrption;
	}

	public Integer getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(Integer historyId) {
		this.historyId = historyId;
	}

	public Publisher getPublisher() {
		return this.publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	public Territory getTerritory() {
		return this.territory;
	}

	public void setTerritory(Territory territory) {
		this.territory = territory;
	}

	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	public String getActionDescrption() {
		return this.actionDescrption;
	}

	public void setActionDescrption(String actionDescrption) {
		this.actionDescrption = actionDescrption;
	}

}
